Performance difference between Numpy array and Python list

In [0]:
import numpy as np

In [0]:
my_arr = np.arange(1000000)

In [0]:
my_list = list(range(1000000))

In [0]:
%time for _ in range(10): my_arr2 = my_arr * 2 # 10 - 100 times faster than pure Python counterpart

CPU times: user 14.5 ms, sys: 14.7 ms, total: 29.2 ms
Wall time: 33.3 ms


In [0]:
%time for _ in range(10): my_list2 = my_list * 2

CPU times: user 198 ms, sys: 28.9 ms, total: 227 ms
Wall time: 231 ms


#### 4.1 The NumPy ndarray: A Multidimensional Array Object

Batch Computations in numpy array

In [0]:
import numpy as np
# Generate some random array of shape 2 x 3
data = np.random.randn(2, 3)
data

array([[ 0.16384098, -0.64116578, -0.64148606],
       [ 1.99115412, -0.23408163, -0.36392117]])

In [0]:
# mathemataical operations
data * 10 # multiply all the elements by 10

array([[ 1.63840977, -6.41165776, -6.41486063],
       [19.91154124, -2.34081627, -3.63921167]])

In [0]:
data + data # add each value to its corresponding cell value 

array([[ 0.32768195, -1.28233155, -1.28297213],
       [ 3.98230825, -0.46816325, -0.72784233]])

ndarray can only contain homogeneous data.

In [0]:
# returns a tuple, containing shape of array:
data.shape

(2, 3)

In [0]:
# returns data type of the array
data.dtype

dtype('float64')

##### Creating ndarrays

Creating ndarrays using **array** function from sequence-like object

In [0]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Nested sequences can be converted into multidimensional array:

In [0]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
arr2.shape

(2, 4)

In [0]:
arr2.ndim # returns the dimension of the array

2

In [0]:
arr1.dtype # np.array tries to infer a good data type

dtype('float64')

In [0]:
arr2.dtype

dtype('int64')

Creating ndarrays using zeros, ones, empty and other methods

In [0]:
# create array of zeros
np.zeros(10) # for 1-d array pass only length of the array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
# for higher dimensions pass desired shape as a tuple
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [0]:
np.empty((2, 3, 2)) # returns uninitialized array of given shape (sometimes with garbage value or zeros)

array([[[3.61057640e-316, 3.71448829e-316],
        [3.95252517e-323, 3.71448829e-316],
        [6.92152587e-310, 3.71448829e-316]],

       [[6.92152587e-310, 0.00000000e+000],
        [3.71451359e-316, 3.71451359e-316],
        [3.71451359e-316, 0.00000000e+000]]])

In [0]:
# similar to range function but for arrays
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##### Data Types for ndarrays

In [0]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [0]:
arr1.dtype

dtype('float64')

In [0]:
arr2.dtype

dtype('int32')

Explicit type casting (**astype()** method) -> **astype()** always creates a new array

In [0]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [0]:
float_arr = arr.astype(np.float64) # casting from 64 bit int to 64 bit float
float_arr.dtype

dtype('float64')

Casting from float to int will truncate decimal values

In [0]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [0]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

String to numeric form

In [0]:
numeric_strings = np.array(['1.25', '-9.6', '4.2'], dtype=np.string_)

In [0]:
numeric_strings.astype(np.float) # Why writing only float? Numpy aliases the Python types to its own equivalent data dtypes

array([ 1.25, -9.6 ,  4.2 ])

Casting using dtype attribute

In [0]:
int_array = np.arange(10)
callibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [0]:
int_array.astype(callibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Shorthands for defining dtype

In [0]:
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

##### Arithmetic with NumPy Arrays

**Vectorization**: Batch operations on data without any for loops. <br/>
Any operations between equal sized arrays applies the operation element wise.

In [0]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [0]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [0]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Arithmetic operations with scalars propogate the scalar argument to each element in the array

In [0]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [0]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Comparision between same sized arrays yield boolean arrays

In [0]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [0]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

**Broadcasting**: Operations between differently sized arrays.

##### Basic Indexing and Slicing

1-D arrays act similarly to Python lists

In [0]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr[5] # value at index 5

5

In [0]:
arr[5:8] # values at index 5, 6, 7

array([5, 6, 7])

In [0]:
arr[5:8] = 12 # broadcast 12 at index 5, 6, 7
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Array slices are **views** on the original array (that is values data is not copied)

In [0]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [0]:
arr_slice[1] = 12345
arr # mutations are updated to the original array

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

Broadcasting with **[:]**

In [0]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

Copying array data

In [0]:
arr_slice = arr[5:8].copy()
arr_slice[0] = 9876
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [0]:
arr_slice

array([9876,   64,   64])

Slicing of Higher Dimensional arrays

In [0]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2] # elements at each index is a 1-D array

array([7, 8, 9])

In [0]:
# accessing individual elements
arr2d[0][1] # element at 1st row and 2nd col

2

In [0]:
# alternate way
arr2d[0, 1]

2

Accessing lower dimensional ndarray from a higher dimensional one

In [0]:
# a 2 x 2 x 3 array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [0]:
# arr3d[0] is a 2 x 3 array
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

Both scalar values and arrays can be assigned to arr3d[0]

In [0]:
old_values = arr3d[0].copy()
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [0]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [0]:
# extracting 1-D values from array
arr3d[1, 0]

array([7, 8, 9])

In [0]:
# above expression is similar to:
x = arr3d[1]
print(x) # a view of the array
print('-------')
x[0] # a view of the array

[[ 7  8  9]
 [10 11 12]]
-------


array([7, 8, 9])

###### Indexing with slices

In [0]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
arr2d[:2] # slicing till 2nd row / sliced along axis 0

array([[1, 2, 3],
       [4, 5, 6]])

Passing multiple slices

In [0]:
arr2d[:2, 1:] # select first 2 rows, and columns from 2nd till last

array([[2, 3],
       [5, 6]])

Getting lower dimensional slices

In [0]:
arr2d[1, :2] # select 2nd row but only fist 2 columns

array([4, 5])

Third column but only first 2 rows

In [0]:
arr2d[:2, 2]

array([3, 6])

Slicing only higher dimensional axes

In [0]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

Assigning to a slice expression assigns to the whole section

In [0]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

##### Boolean Indexing

Boolean indexing always creates a **copy** of the data.<br/>
Suppose each name corresponds to a row in the data array.

In [0]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4) # generate random normally distributed array of the given shape
data

array([[ 1.20342972, -1.05266293, -0.26182714,  1.06598849],
       [-0.43870061, -0.04347591, -0.3759416 , -0.46255953],
       [ 0.71126848, -1.15226834, -0.76900477, -0.92000369],
       [ 1.45278092, -0.36251045, -0.35591243,  2.16775602],
       [-0.44365449, -2.02860099, -0.25296516, -0.82107172],
       [ 0.29630211, -0.90417745,  0.32861467, -0.50289157],
       [ 0.55428513, -1.27585501,  1.04591641,  1.11754477]])

In [0]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

Extract rows where name is **Bob**



In [0]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [0]:
# index with the help of names array
data[names == 'Bob']

array([[ 1.20342972, -1.05266293, -0.26182714,  1.06598849],
       [ 1.45278092, -0.36251045, -0.35591243,  2.16775602]])

Select rows with name == 'Bob' and index the column from 2 onwards

In [0]:
data[names == 'Bob', 2:]

array([[-0.26182714,  1.06598849],
       [-0.35591243,  2.16775602]])

In [0]:
# another example
data[names == 'Bob', 3]

array([1.06598849, 2.16775602])

Select everything but Bob

In [0]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [0]:
data[names != 'Bob']

array([[-0.43870061, -0.04347591, -0.3759416 , -0.46255953],
       [ 0.71126848, -1.15226834, -0.76900477, -0.92000369],
       [-0.44365449, -2.02860099, -0.25296516, -0.82107172],
       [ 0.29630211, -0.90417745,  0.32861467, -0.50289157],
       [ 0.55428513, -1.27585501,  1.04591641,  1.11754477]])

In [0]:
# alternate way
data[~(names == 'Bob')] # ~ is for negation

array([[-0.43870061, -0.04347591, -0.3759416 , -0.46255953],
       [ 0.71126848, -1.15226834, -0.76900477, -0.92000369],
       [-0.44365449, -2.02860099, -0.25296516, -0.82107172],
       [ 0.29630211, -0.90417745,  0.32861467, -0.50289157],
       [ 0.55428513, -1.27585501,  1.04591641,  1.11754477]])

In [0]:
# another way
cond = names == 'Bob'
data[~cond]

array([[-0.43870061, -0.04347591, -0.3759416 , -0.46255953],
       [ 0.71126848, -1.15226834, -0.76900477, -0.92000369],
       [-0.44365449, -2.02860099, -0.25296516, -0.82107172],
       [ 0.29630211, -0.90417745,  0.32861467, -0.50289157],
       [ 0.55428513, -1.27585501,  1.04591641,  1.11754477]])

Combining multiple conditions (**and** and **or** keywords does not works with boolean arrays)

In [0]:
mask = (names == 'Bob') | (names == 'Will') # | for or
mask

array([ True, False,  True,  True,  True, False, False])

In [0]:
data[mask]

array([[ 1.20342972, -1.05266293, -0.26182714,  1.06598849],
       [ 0.71126848, -1.15226834, -0.76900477, -0.92000369],
       [ 1.45278092, -0.36251045, -0.35591243,  2.16775602],
       [-0.44365449, -2.02860099, -0.25296516, -0.82107172]])

Setting negative values to 0

In [0]:
data[data < 0] = 0
data

array([[1.20342972, 0.        , 0.        , 1.06598849],
       [0.        , 0.        , 0.        , 0.        ],
       [0.71126848, 0.        , 0.        , 0.        ],
       [1.45278092, 0.        , 0.        , 2.16775602],
       [0.        , 0.        , 0.        , 0.        ],
       [0.29630211, 0.        , 0.32861467, 0.        ],
       [0.55428513, 0.        , 1.04591641, 1.11754477]])

Setting whole rows or columns with 1-D boolean array

In [0]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.29630211, 0.        , 0.32861467, 0.        ],
       [0.55428513, 0.        , 1.04591641, 1.11754477]])

##### Fancing Indexing

(indexing using integer arrays) <br/>
Always **copies** data into a new array.

In [0]:
arr = np.empty((8, 4))
for i in range(8):
  arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

Selecting out a subset of the rows in a particular order

In [0]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

Using negative indices to select rows

In [0]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

Passing multiple index arrays

In [0]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [0]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Selecting a subset of the matrix

In [0]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

##### Transposing Arrays and Swapping Axes

Transposing returns a **view** (without copying)

In [0]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
# transposing with .T attribute
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Example: Computing the inner matrix product

In [0]:
arr = np.random.randn(6, 3)
arr

array([[-0.8462071 ,  2.26053532, -1.75712724],
       [-0.9119238 , -0.06676154, -0.89295238],
       [ 2.82236309, -1.28544071, -0.76978925],
       [ 2.19804948, -0.52983987,  1.98032818],
       [-0.48363537,  0.15097041,  0.19107502],
       [ 2.46474634, -1.00983377, -1.22135178]])

In [0]:
np.dot(arr.T, arr)

array([[20.65370405, -9.20659299,  1.37869967],
       [-9.20659299,  8.09012146, -2.70996275],
       [ 1.37869967, -2.70996275,  9.92734514]])

For higher dimensions **transpose()** method is suitable

In [0]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [0]:
arr.strides

(64, 32, 8)

In [0]:
# it requires tuple of axis
arr.transpose((1, 0, 2)) # we are swapping 1st and 2nd axis, for more understanding: (https://stackoverflow.com/a/32034565/8438777)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [0]:
arr.transpose((1, 0, 2)).strides

(32, 64, 8)

**swapaxes()** method (also returns **view**)

In [0]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [0]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [0]:
arr.swapaxes(0, 1)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

#### 4.2 Universal Functions: Fast Element-Wise Array Functions

**ufuncs**: performs element wise operations <br/>
If input = single array, function = **unary ufunc**

In [0]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [0]:
np.exp(arr) #calculates ex for each x in your list where e is Euler's number (approximately 2.718) (https://stackoverflow.com/a/31952092/8438777)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

input = 2 arrays, function = **binary ufunc**

In [0]:
x = np.random.randn(8)
y = np.random.randn(8)
x

array([ 0.13990753, -1.73297139,  0.32554397, -0.16760517,  0.46678969,
       -0.72754096, -0.26482551,  1.06761629])

In [0]:
y

array([-0.5126777 ,  0.42143663, -0.0081001 , -0.03204254, -1.55705897,
       -0.01528991,  0.12498092, -0.31184363])

In [0]:
np.maximum(x, y)# compute element-wise maximum

array([ 0.13990753,  0.42143663,  0.32554397, -0.03204254,  0.46678969,
       -0.01528991,  0.12498092,  1.06761629])

some **ufuncs** like **modf** returns multiple arrays

In [0]:
arr = np.random.randn(7) *5
arr

array([ 9.03297639, -3.04584689, -2.04326878,  2.48630672,  1.0643136 ,
        5.56002856,  0.39563897])

In [0]:
remainder, whole_part = np.modf(arr)
remainder

array([ 0.03297639, -0.04584689, -0.04326878,  0.48630672,  0.0643136 ,
        0.56002856,  0.39563897])

In [0]:
whole_part

array([ 9., -3., -2.,  2.,  1.,  5.,  0.])

inplace modification with second optional argument

In [7]:
import numpy as np
arr = np.random.randn(7) *5
arr

array([ 7.40583167,  3.64975251,  7.81629928,  1.108775  , -6.70988669,
       -9.47418444, -6.47079215])

In [8]:
np.sqrt(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.72136577, 1.91043255, 2.79576453, 1.05298385,        nan,
              nan,        nan])

In [9]:
arr # operation not performed inplace

array([ 7.40583167,  3.64975251,  7.81629928,  1.108775  , -6.70988669,
       -9.47418444, -6.47079215])

In [10]:
np.sqrt(arr, arr) # inplace

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([2.72136577, 1.91043255, 2.79576453, 1.05298385,        nan,
              nan,        nan])

In [11]:
arr

array([2.72136577, 1.91043255, 2.79576453, 1.05298385,        nan,
              nan,        nan])

In [12]:
arr = np.random.randn(7) *5
arr

array([-6.29667511, -8.47900407, -0.4285393 ,  2.08455888,  1.90953973,
        4.86953701, -4.23860185])

In [13]:
np.exp(arr)

array([1.84242045e-03, 2.07785540e-04, 6.51459990e-01, 8.04104362e+00,
       6.74998126e+00, 1.30260594e+02, 1.44277499e-02])

In [14]:
arr

array([-6.29667511, -8.47900407, -0.4285393 ,  2.08455888,  1.90953973,
        4.86953701, -4.23860185])

In [15]:
np.exp(arr, arr)

array([1.84242045e-03, 2.07785540e-04, 6.51459990e-01, 8.04104362e+00,
       6.74998126e+00, 1.30260594e+02, 1.44277499e-02])

In [16]:
arr

array([1.84242045e-03, 2.07785540e-04, 6.51459990e-01, 8.04104362e+00,
       6.74998126e+00, 1.30260594e+02, 1.44277499e-02])

Other Unary funcs

In [18]:
# absolute values element-wise for integers
print(f'abs: {np.abs(np.array([-3, 4, 5, -9, 2]))}\n')
# absolute values element-wise for floating point / complex values
print(f'fabs: {np.fabs(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')
# compute square element-wise
print(f'square: {np.square(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')
# natural log (base e)
print(f'log: {np.log(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')
# log base 10
print(f'log10: {np.log10(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')
# log base 2
print(f'log2: {np.log2(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')
# log(1 + x)s
print(f'log1p: {np.log1p(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')

abs: [3 4 5 9 2]

fabs: [3.2   4.09  5.3   9.9   2.594]

square: [10.24     16.7281   28.09     98.01      6.728836]

log: [       nan 1.40854497 1.66770682        nan 0.95320109]

log10: [       nan 0.61172331 0.72427587        nan 0.41396997]

log2: [       nan 2.03210084 2.40599236        nan 1.37517848]

log1p: [       nan 1.62727783 1.84054963        nan 1.27926579]



/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in log
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in log10
  if __name__ == '__main__':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in log2
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in log1p
  del sys.path[0]


In [19]:
# compute sign of each element -> (1 (positive), 0 (zero), -1 (negative))
print(f'sign: {np.sign(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')
# compute the ceiling of each element (smallest integer gnp.array([-3.2, 4.09, 5.3, -9.9, 2.594])reater than or equal to that number)
print(f'ceil: {np.ceil(np.array([-3, 4.09, 5.3, -9.9, 2.594]))}\n')
# compute the floor (largest integer less than or equal to each element)
print(f'floor: {np.floor(np.array([-3, 4.09, 5.3, -9.9, 2.594]))}\n')
# Round elements to nearest integer
print(f'rint: {np.rint(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')
# Returns boolean indicating wether each value is NaN or not
print(f'isnan: {np.isnan(np.array([-3.2, 4.09, float("NaN"), -9.9, 2.594]))}\n')
# Returns boolean array indicating wether each element is finite or infinte / nan
print(f'isfinite: {np.isfinite(np.array([-3.2, float("INF"), 5.3, -9.9, float("nan")]))}\n')

sign: [-1.  1.  1. -1.  1.]

ceil: [-3.  5.  6. -9.  3.]

floor: [ -3.   4.   5. -10.   2.]

rint: [ -3.   4.   5. -10.   3.]

isnan: [False False  True False False]

isfinite: [ True False  True  True False]



In [20]:
# Returns boolean array indicating wether each element is infinite or not
print(f'isinf: {np.isinf(np.array([-3.2, float("INF"), 5.3, -9.9, float("nan")]))}\n')
# compute truth value of not x element-wise
print(f'logical_not: {np.logical_not(np.array([True, float("INF"), 5.3, -9.9, False]))}\n')
# equilent to np.logical_not() but only works on boolean arrays
print(f'~: {~(np.array([True, False, True, True, False]))}\n')

isinf: [False  True False False False]

logical_not: [False False False False  True]

~: [False  True False False  True]



In [21]:
# Regular hyperbolic trignometric functions
print(f'cos: {np.cos(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')
print(f'cosh: {np.cosh(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')
print(f'sin: {np.sin(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')
print(f'sinh: {np.sinh(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')
print(f'tan: {np.tan(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')
print(f'tanh: {np.tanh(np.array([-3.2, 4.09, 5.3, -9.9, 2.594]))}\n')

cos: [-0.99829478 -0.58297784  0.55437434 -0.88919115 -0.85378034]

cosh: [1.22866462e+01 2.98783155e+01 1.00170901e+02 9.96518524e+03
 6.72895901e+00]

sin: [ 0.05837414 -0.81248805 -0.83226744  0.45753589  0.52063339]

sinh: [-1.22458840e+01  2.98615762e+01  1.00165909e+02 -9.96518519e+03
  6.65423846e+00]

tan: [-0.05847385  1.393686   -1.5012734  -0.51455291 -0.60979783]

tanh: [-0.9966824   0.99943975  0.99995017 -0.99999999  0.98889567]



Other Binary ufuncs

In [22]:
import numpy as np
x = np.random.randint(1, 100+1, 10)
y = np.random.randint(1, 100+1, 10)
x

array([19, 68, 38, 54, 32, 85, 72, 23, 59, 57])

In [23]:
y

array([ 97,   3,  54,   9, 100,  55,   6,  57,   9,  12])

In [24]:
print(f'add: {np.add(x, y)}\n')
print(f'subtract: {np.subtract(x, y)}\n')

print(f'multiply: {np.multiply(x, y)}\n')
print(f'devide: {np.divide(x, y)}\n')

#truncating remainder
print(f'floor_divide: {np.floor_divide(x, y)}\n')

#raise elements of the first array to powers indicating the second array
print(f'power: {np.power(x, y)}\n')

print(f'maximum: {np.maximum(np.array([97, 39, 65, 27, float("nan"), 49, float("inf"),  2, 31, 96]), y)}\n')
# ignores nan
print(f'fmax: {np.fmax(np.array([97, 39, 65, 27, float("nan"), 49, float("inf"),  2, 31, 96]), y)}\n')

print(f'minimum: {np.minimum(np.array([97, 39, 65, 27, float("nan"), 49, float("inf"),  2, 31, 96]), y)}\n')
# ignores nan
print(f'fmin: {np.fmin(np.array([97, 39, 65, 27, float("nan"), 49, float("inf"),  2, 31, 96]), y)}\n')

add: [116  71  92  63 132 140  78  80  68  69]

subtract: [-78  65 -16  45 -68  30  66 -34  50  45]

multiply: [1843  204 2052  486 3200 4675  432 1311  531  684]

devide: [ 0.19587629 22.66666667  0.7037037   6.          0.32        1.54545455
 12.          0.40350877  6.55555556  4.75      ]

floor_divide: [ 0 22  0  6  0  1 12  0  6  4]

power: [-3997973556274249581               314432  7944349742681554944
     3904305912313344                    0  6100997309985656605
         139314069504  -495679767775353257     8662995818654939
 -4345326813971635423]

maximum: [97. 39. 65. 27. nan 55. inf 57. 31. 96.]

fmax: [ 97.  39.  65.  27. 100.  55.  inf  57.  31.  96.]

minimum: [97.  3. 54.  9. nan 49.  6.  2.  9. 12.]

fmin: [ 97.   3.  54.   9. 100.  49.   6.   2.   9.  12.]



In [25]:
# copy sign of elements from second array to first array element wise
print(f'copysign: {np.copysign(np.array([97, 39, -65, -27, float("nan"), 49, -float("inf"),  2, -31, 96]), \
                               np.array([-86, 31, 74, 93, -31, 26, 75, 43, 91, 60]))}\n')

# element wise comparision (does not supports nan values), equivalent to '>'
print(f'greater: {np.greater(np.array([97, 39, -65, -27, 49, -float("inf"),  2, -31, 96]), \
                               np.array([-86, 31, 74, -31, 26, 75, 43, 91, 60]))}\n')

# equivalent to '>='
print(f'greater_equal: {np.greater_equal(np.array([97, 39, -65, -27, 49, -float("inf"),  2, -31, 96]), \
                               np.array([-86, 31, 74, -31, 26, 75, 43, 91, 60]))}\n')

# equivalent to '<'
print(f'less: {np.less(np.array([97, 39, -65, -27, 49, -float("inf"),  2, -31, 96]), \
                               np.array([-86, 31, 74, -31, 26, 75, 43, 91, 60]))}\n')

# equivalent to '<='
print(f'less_equal: {np.less_equal(np.array([97, 39, -65, -27, 49, -float("inf"),  2, -31, 96]), \
                               np.array([-86, 31, 74, -31, 26, 75, 43, 91, 60]))}\n')

# equivalent to '='
print(f'equal: {np.equal(np.array([97, 39, -65, -27, 49, -float("inf"),  2, -31, 96]), \
                               np.array([-86, 31, 74, -31, 26, 75, 43, 91, 60]))}\n')

# equivalent to '!='
print(f'not_equal: {np.not_equal(np.array([97, 39, -65, -27, 49, -float("inf"),  2, -31, 96]), \
                               np.array([-86, 31, 74, -31, 26, 75, 43, 91, 60]))}\n')

copysign: [-97.  39.  65.  27.  nan  49.  inf   2.  31.  96.]

greater: [ True  True False  True  True False False False  True]

greater_equal: [ True  True False  True  True False False False  True]

less: [False False  True False False  True  True  True False]

less_equal: [False False  True False False  True  True  True False]

equal: [False False False False False False False False False]

not_equal: [ True  True  True  True  True  True  True  True  True]



In [26]:
# equivalent to &
print(f'logical_and: {np.logical_and(np.array([97, 39, -65, -27, 0, -float("inf"),  2, -31, 96]), \
                               np.array([-86, 0, 74, -31, 26, 75, 43, 91, 60]))}\n')

# equivalent to |
print(f'logical_or: {np.logical_or(np.array([97, 0, -65, -27, 0, -float("inf"),  2, -31, 0]), \
                               np.array([-86, 0, 74, -31, 26, 75, 43, 91, 0]))}\n')

# equivalent to ^
print(f'logical_xor: {np.logical_xor(np.array([97, 0, -65, -27, 0, -float("inf"),  2, -31, 0]), \
                               np.array([-86, 0, 74, -31, 26, 75, 43, 91, 0]))}')

logical_and: [ True False  True  True False  True  True  True  True]

logical_or: [ True False  True  True  True  True  True  True False]

logical_xor: [False False False False  True False False False False]


#### 4.3 Array-Oriented Programming with Arrays